links:
    - text: 'Gmail'
      fa: 'fa-inbox'
      target: 'https://mail.google.com/mail/u/0/#inbox'
    - text: 'Google'
      fa: 'fa-magnifying-glass'
      target: 'https://www.google.com/'
    - text: 'News'
      fa: 'fa-newspaper'
      target: 'https://news.google.com/'
    - text: 'Radio'
      fa: 'fa-radio'
      target: 'https://tunein.com/radio/home/'
    - text: 'Weather'
      fa: 'fa-sun'
      target: 'https://weather.com/weather/today/l/39.59,-80.25'
    - text: 'Wikipedia'
      fa: 'fa-book-atlas'
      target: 'https://www.wikipedia.org/'

buttons:
    - text: 'Documents'
      fa: 'fa-file-lines'
      target: 'Documents'
    - text: 'Downloads'
      fa: 'fa-cloud-arrow-down'
      target: 'Downloads'
    - text: 'Music'
      fa: 'fa-music'
      target: 'Music'
    - text: 'Pictures'
      fa: 'fa-camera-retro'
      target: 'Pictures'

